let ME;const V={
async dash(el){const[u,a]=await Promise.all([sb.from('users').select('ssc_gd_premium,is_active,created_at'),sb.from('attempts').select('score')]);const us=u.data||[],at=a.data||[];
el.innerHTML=`<div class="grid">${[['Total Users',us.length],['Premium',us.filter(x=>x.ssc_gd_premium).length],['Free',us.filter(x=>!x.ssc_gd_premium).length],['Active',us.filter(x=>x.is_active).length],['Total Attempts',at.length],['Average Score',f1(avg(at.map(x=>x.score)))],['Average %',f1(avg(at.map(x=>x.score/1.6)))+'%']].map(([k,v])=>card(k,v)).join('')}</div>`},
async users(el){const{data}=await sb.from('users').select('name,ssc_gd_premium,is_active,created_at,attempts(score)').eq('role','user');
el.innerHTML='<div class="table-wrapper"><table><tr><th>Name</th><th>Premium</th><th>Tests</th><th>Avg</th><th>Best</th></tr>'+(data||[]).slice(0,200).map(u=>{const s=(u.attempts||[]).map(x=>x.score);return`<tr><td>${esc(u.name)}</td><td>${u.ssc_gd_premium?'Yes':'No'}</td><td>${s.length}</td><td>${f1(avg(s))}</td><td>${f1(Math.max(0,...s))}</td></tr>`}).join('')+'</table></div>'},
async results(el){const{data}=await sb.from('attempts').select('*,users(name)').order('created_at',{ascending:false}).limit(200);
el.innerHTML='<div class="table-wrapper"><table><tr><th>User</th><th>Test</th><th>#</th><th>Score</th><th>C</th><th>W</th><th>S</th><th>%</th><th>Time</th><th>Date</th></tr>'+(data||[]).map(a=>`<tr><td>${esc(a.users?.name)}</td><td>${esc(a.test_id)}</td><td>${a.attempt_number}</td><td>${f1(a.score)}</td><td>${a.correct}</td><td>${a.wrong}</td><td>${a.skipped}</td><td>${f1(a.score/1.6)}</td><td>${Math.round(a.time_taken/60)}m</td><td>${new Date(a.created_at).toLocaleDateString()}</td></tr>`).join('')+'</table></div>'},
async analytics(el){const{data}=await sb.from('attempts').select('test_id,score,correct,wrong,skipped,sections');const by={},sub={};
(data||[]).forEach(a=>{const o=by[a.test_id]=by[a.test_id]||{n:0,s:0};o.n++;o.s+=a.score;(a.sections||[]).forEach(s=>{const k=sub[s.title]=sub[s.title]||{c:0,t:0};k.c+=s.correct;k.t+=s.correct+s.wrong+s.skipped})});
const sc=(data||[]).map(a=>a.score);
el.innerHTML=`<div class="grid">${card('Highest',f1(Math.max(0,...sc)))}${card('Lowest',f1(sc.length?Math.min(...sc):0))}${card('Average',f1(avg(sc)))}</div><h3>Per test</h3><div class="table-wrapper"><table><tr><th>Test</th><th>Attempts</th><th>Avg score</th></tr>${Object.entries(by).sort((a,b)=>b[1].n-a[1].n).map(([k,o])=>`<tr><td>${esc(k)}</td><td>${o.n}</td><td>${f1(o.s/o.n)}</td></tr>`).join('')}</table></div><h3>Per subject (accuracy)</h3><div class="grid">${Object.entries(sub).map(([k,o])=>`<div class="card"><b>${esc(k)}</b><div class="bar"><i style="width:${o.c/(o.t||1)*100}%"></i></div></div>`).join('')}</div>`},
async scoreboard(el){el.innerHTML=await scoreboardHTML(sb)}};
async function adminNav(n){$$('[data-v]').forEach(b=>b.classList.toggle('on',b.dataset.v===n));$('#drawer').classList.remove('open');const el=$('#panel');el.innerHTML='<p class="muted">Loading…</p>';
try{await(window.AV||V)[n](el)}catch(e){el.innerHTML='<p class="muted">Could not load data (access denied or network error).</p>'}}
document.addEventListener('DOMContentLoaded',async()=>{if(document.body.dataset.role!=='sub_admin')return;ME=await guard('sub_admin');if(!ME)return;$('#who').textContent=ME.name;
$$('[data-v]').forEach(b=>b.onclick=()=>adminNav(b.dataset.v));$('#burger').onclick=()=>$('#drawer').classList.toggle('open');adminNav('dash')});
