const OUT=u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.mobile)}</td><td>${esc(u.email||'')}</td><td>${u.role}</td><td>${u.ssc_gd_premium?'Yes':'No'}</td><td>${u.is_active?'Yes':'No'}</td><td>${new Date(u.created_at).toLocaleDateString()}</td>
<td class="acts"><button onclick="upd('${u.id}',{ssc_gd_premium:${!u.ssc_gd_premium}})">${u.ssc_gd_premium?'Remove':'Approve'} Premium</button><button onclick="upd('${u.id}',{is_active:${!u.is_active}})">${u.is_active?'Deactivate':'Activate'}</button><select onchange="upd('${u.id}',{role:this.value})">${['user','sub_admin','admin'].map(r=>`<option ${r===u.role?'selected':''}>${r}</option>`).join('')}</select></td></tr>`;
async function upd(id,p){const{error}=await sb.from('users').update(p).eq('id',id);toast(error?'Update failed: '+error.message:'Updated');adminNav($('[data-v].on')?.dataset.v||'users')}
async function usersView(el,role){const q=(window._q||'').toLowerCase();let{data}=await sb.from('users').select(SAFE).order('created_at',{ascending:false});data=(data||[]).filter(u=>(!role||u.role===role)&&(u.name+u.mobile+(u.email||'')).toLowerCase().includes(q));
el.innerHTML=(role?'':'<input class="search" placeholder="Search name, mobile, email" oninput="window._q=this.value;clearTimeout(window._t);window._t=setTimeout(()=>adminNav(\'users\'),400)" value="'+esc(window._q||'')+'">')+'<div class="table-wrapper"><table><tr><th>Name</th><th>Mobile</th><th>Email</th><th>Role</th><th>Premium</th><th>Active</th><th>Joined</th><th>Actions</th></tr>'+data.slice(0,200).map(OUT).join('')+'</table></div>'}
window.AV={...V,
users:el=>usersView(el),subadmins:el=>usersView(el,'sub_admin'),
async tests(el){el.innerHTML='<div class="grid">'+Array.from({length:10},(_,i)=>`<div class="card"><b>Full Mock ${String(i+1).padStart(2,'0')}</b><p class="muted">ssc-gd-full-${String(i+1).padStart(2,'0')} · questions on GitHub JSON</p></div>`).join('')+SUBJ.map(([k,t])=>`<div class="card"><b>${t}</b><p class="muted">subjects/${k}/</p></div>`).join('')+'</div>'},
async referrals(el){const{data}=await sb.from('referral_codes').select('*').order('created_at',{ascending:false});
el.innerHTML=`<div class="card"><input id="rc" placeholder="CODE"><select id="rt"><option>percentage</option><option>fixed</option></select><input id="rv" type="number" placeholder="Value"><button class="btn" onclick="addRef(this)">Create Code</button></div><div class="table-wrapper"><table><tr><th>Code</th><th>Type</th><th>Value</th><th>Active</th><th></th></tr>${(data||[]).map(r=>`<tr><td>${esc(r.code)}</td><td>${r.discount_type}</td><td>${r.discount_value}</td><td>${r.is_active}</td><td><button onclick="togRef('${r.id}',${!r.is_active})">${r.is_active?'Deactivate':'Activate'}</button></td></tr>`).join('')}</table></div>`}};
async function addRef(b){await busy(b,async()=>{const{error}=await sb.from('referral_codes').insert({code:$('#rc').value.trim(),discount_type:$('#rt').value,discount_value:+$('#rv').value,is_active:true});toast(error?error.message:'Created');adminNav('referrals')})}
async function togRef(id,v){await sb.from('referral_codes').update({is_active:v}).eq('id',id);adminNav('referrals')}
document.addEventListener('DOMContentLoaded',async()=>{if(document.body.dataset.role!=='admin')return;ME=await guard('admin');if(!ME)return;$('#who').textContent=ME.name;
$$('[data-v]').forEach(b=>b.onclick=()=>adminNav(b.dataset.v));$('#burger').onclick=()=>$('#drawer').classList.toggle('open');adminNav('dash')});
